---
options:
  # Don't merge default rules
  merge-default-rules: false
files:
  include: '**/*.s+(a|c)ss'
  ignore: 
      - '**/_shame.scss'
rules:
  quotes:
      - 1
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq
  no-ids: 2
  no-important: 2
  hex-notation:
    - 2
    -
      style: lowercase
  indentation:
    - 1
    -
      size: 2
  property-sort-order:
    - 1
    -
      ignore-custom-properties: true
  space-after-colon:
    - 1
  zero-unit:
    - 1
  leading-zero:
    - 1
  no-trailing-zero:
    - 1
  empty-line-between-blocks:
    - 1
